apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pgopher
commonLabels:
  app.kubernetes.io/name: pgopher
resources:
  - namespace.yml
  - deploy.yml
configMapGenerator:
  - name: pgopher
    files:
      - config.yml
