apiVersion: v1
kind: ServiceAccount
metadata:
  name: pgopher
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pgopher-secrets
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pgopher-secrets
subjects:
  - kind: ServiceAccount
    name: pgopher
roleRef:
  kind: Role
  name: pgopher-secrets
  apiGroup: rbac.authorization.k8s.io
